name: manifestacion_numerica_grabovoi
description: App espiritual basada en los códigos de Grigori Grabovoi
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI y Diseño Místico
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  lottie: ^3.1.2
  flutter_svg: ^2.0.9
  flutter_staggered_animations: ^1.1.1
  animations: ^2.0.10
  
  # Estado y Navegación
  provider: ^6.1.1
  
  # Base de datos y almacenamiento
  # supabase_flutter: ^2.4.3  # Comentado para compilación Android (conflicto con app_links)
  shared_preferences: ^2.3.1
  path_provider: ^2.1.3
  
  # Gráficos y Visualización
  fl_chart: ^0.67.0
  
  # Utilidades
  intl: ^0.19.0
  http: ^1.2.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.2

flutter:
  uses-material-design: true
  
  assets:
    - lib/data/
  #   - assets/images/
  #   - assets/audios/
  #   - assets/lottie/
  #   - assets/icons/
    
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700

