name: manifestacion_numerica_grabovoi
description: Una aplicación de bienestar holístico con secuencias numéricas Grabovoi
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI y Diseño
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  lottie: ^3.0.0
  
  # Estado y Navegación
  provider: ^6.1.1
  go_router: ^13.0.0
  
  # Base de datos y almacenamiento
  # supabase_flutter: ^2.3.4  # Comentado temporalmente para compilación Android
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Notificaciones y recordatorios
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2
  
  # Audio y multimedia
  audioplayers: ^5.2.1
  just_audio: ^0.9.36
  
  # Utilidades
  intl: ^0.19.0
  uuid: ^4.3.3
  flutter_markdown: ^0.6.18
  url_launcher: ^6.2.4
  # share_plus: ^10.1.2  # Comentado temporalmente para compilación Android
  
  # Bienestar
  # breathing_collection: ^0.0.5  # Opcional - implementado manualmente
  # flutter_fortune_wheel: ^1.3.1  # Opcional

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/images/
  #   - assets/audios/
  #   - assets/lottie/
  #   - assets/icons/
    
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700

