-- Create table for Mural Messages
create table if not exists public.mural_messages (
  id bigint generated by default as identity primary key,
  title text not null,
  message text not null,
  image_url text,
  action_url text,
  is_active boolean default true,
  type text default 'info', -- 'info', 'event', 'alert', 'promotion'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  expires_at timestamp with time zone
);

-- Enable RLS
alter table public.mural_messages enable row level security;

-- Create policy to allow everyone to read active messages
create policy "Public messages are viewable by everyone"
  on public.mural_messages for select
  using ( is_active = true );

-- Create policy to allow only authenticated users (admins/service role) to insert/update/delete
-- For now, we'll assume manual insertion via dashboard or future admin panel
-- but we can add a policy for authenticated users if needed later.
-- Currently, we rely on the fact that public anon key only has SELECT access if we configure it so,
-- or we just use the dashboard which bypasses RLS.

-- Comment on table
comment on table public.mural_messages is 'Messages for the Community Mural/Board';
